### ISSUE TITLE
[Thread] Issues which should be fixed before the first release

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/libcobblersignatures#31]
This is a Thread which will collect all usability issues, as well as code issues, I am able to find during my session at the 2021-06-18. Every Box will be discussed with @nodeg.

This issue will be closed when all points are discussed and splitout issues are created in case we decide to act upon it.

- [x] There is no option to pretty print the output. - https://github.com/cobbler/libcobblersignatures/pull/34
- [x] There is no warning when adding a breed with the same name a second time. - https://github.com/cobbler/libcobblersignatures/pull/35
- [x] Current master signatures are not importable. - #37
- [x] #74
- [x] The properties in the library are not documented - https://github.com/cobbler/libcobblersignatures/pull/33
- [x] ~~The Code Autodoc could be pulled one level up.~~ --> Autodoc generates the `modules.rst` file automatically
- [x] The enums should be split out of the models. - https://github.com/cobbler/libcobblersignatures/pull/36
- [x] Default and missing values should be skipped during im and export. #37 
- [x] ~~Add typehints for the docs - https://github.com/agronholm/sphinx-autodoc-typehints~~ --> This is done automatically by the next regeneration. Sphinx now supports type annotations.
- [x] Move code from `signatures.py` into `__init__.py` since it makes the imports easier for consumers. - https://github.com/cobbler/libcobblersignatures/pull/36
- [x] ~~Autoconversion of `null` values to skipped values.~~ (see above)
- [x] Publish the package to the testing PyPi - https://github.com/cobbler/libcobblersignatures/pull/32
- [x] Publish the package to PyPi after this issue was closed as Version 0.2.0
- [x] Add Wiki Page with Information on how to regenerate the Autodoc etc. - https://github.com/cobbler/libcobblersignatures/wiki/Documentation
- [x] Create and integrate JSON Schema in this library - https://github.com/cobbler/libcobblersignatures/issues/39
- [x] Fix the stacktrace about editing array values in the library - https://github.com/cobbler/libcobblersignatures/pull/40

**Comment by SchoolGuy** [comment]
- [ ] Publish the package to the testing PyPi
- [ ] Publish the package to PyPi after this issue was closed as Version 0.1.0

**Comment by SchoolGuy** [comment]
- [ ] Add Wiki Page with Information on how to regenerate the Autodoc etc.

**Comment by SchoolGuy** [comment]
I think as a last issue we should takle:

- [ ] Create and integrate JSON Schema in this library - https://github.com/cobbler/libcobblersignatures/issues/39

**Comment by SchoolGuy** [comment]
I have decided that this issue is not required anymore as all points are either done or converted to dedicated issues.
